name: Update infrastructure manifest

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  workflow_run:
    workflows: ['Create and Commit Next-Build Docker Image']
    types: [completed]
    branches: [main]

jobs:
  update-manifest:
    if: ${{ !(github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure') }}
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ inputs.image_tag }}
    steps:
      - name: 'Download tag artifact'
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/github-script@v7
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "tag.txt"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/tag.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        if: ${{ github.event_name == 'workflow_run' }}
        run: unzip tag.zip

      - name: 'Read tag version'
        if: ${{ github.event_name == 'workflow_run' }}
        run: |
          echo "IMAGE_TAG=$(cat tag.txt)" >> $GITHUB_ENV

      # If this is triggered via workflow_run, update all 4 app/environment combinations.
      - name: Update image and helm chart versions, all apps and envs
        if: ${{ github.event_name == 'workflow_run' }}
        run: |
            pushd test
            yq e -i '.deployment.container.image = imageurl/dsva/next-build-node:${{ env.IMAGE_TAG }}"' values.yaml
            popd 
      - name: Add and Commit helm chart changes
        if: ${{ github.event_name == 'workflow_run' }}
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          add: '*.yaml'
          cwd: test
          author_name: anything
          author_email: scrubbed@scrubbed.com
          message: 'msg ${{ env.IMAGE_TAG }}'
